daily_questions = [
    "What's your favorite song right now?",
    "Best album of all time?",
    "Which artist would you love to see live?",
    "What’s your go-to genre?",
    "What album changed your life?",
    "What’s the best concert you’ve been to?",
    "Which artist would you collaborate with?",
    "What song defines your mood today?",
    "What music do you play to get inspired?",
    "Which song would you recommend to a friend?",
    "If you could visit any music era, which one?",
    "What’s the most creative music video?",
    "Favorite album cover art?",
    "What’s your ultimate playlist?",
    "What’s the most underrated song?",
    "If your life had a soundtrack, what would it be?",
    "Which artist should reunite for a final tour?",
    "What’s a genre you think is underrated?",
    "What’s the most relatable song lyric?",
    "Discovered any good albums recently?",
    "What’s your latest song discovery?",
    "Your favorite karaoke song?",
    "Who has the best music taste?",
    "What song motivates you?",
    "Best road trip song?",
    "How do you find new music?",
    "Favorite instrument?",
    "If you could live in an album world, which one?",
    "Favorite music meme?",
    "What’s your perfect day playlist?",
    "Rock or pop?",
    "Should artists get paid more by streaming services?",
    "Vinyl or digital?"
]
